### ISSUE TITLE
Switch confirmation dialog button order

### ISSUE THREAD

**Issue by megadr01d** [nao-pon/elFinder-nightly#10]
@nao-pon elFinder tries to mimic Finder but confirmation dialog buttons appear in the wrong order. By default, in OS X, the **Cancel** button is on the left and the action button on the right. This looks somewhat strange in elFinder.

Although this is not a big thing, is there an easy way to change the button order for all confirmation dialogs? If it requires lots of changes then it's not worth it.

![screencap-1434234325751](https://cloud.githubusercontent.com/assets/9649385/8146186/a71cc88e-1223-11e5-8b5d-fb34b8020b65.png)

![screencap-1434233951355](https://cloud.githubusercontent.com/assets/9649385/8146167/f6cb7d4a-1222-11e5-9011-708d45000876.png)

**Comment by nao-pon** [comment]
@megadr01d :+1: 
About Yes/No order, Windows is Yes - No but other platform is No - Yes...
So I think change order by each platforms. :laughing:

**Comment by megadr01d** [comment]
@nao-pon :+1:

Wow, thanks nao-pon, you even had the concern to change it by platform. When you're used to work on a specific platform, visual memory of UIs can impact your workflow.

Just updated to 2.1-7b47cb8 and it's working great in OS X. I finished all the small cosmetic changes I needed in elFinder and I must say your work has proven to be very stable.

Thanks again for the hard work.

**Comment by nao-pon** [comment]
Not at all ! :-D
