### ISSUE TITLE
quarantine URL configuration not exists

### ISSUE THREAD

**Issue by standus** [nao-pon/elFinder-nightly#11]
Hi,

I would like to have ".quarantine" on one global place, so I changed code to:
$this->options['quarantine'] = 'tmp/.quarantine';
but now is problem that I have many many errors mkdir(), because elfinder class want to create directory in /image folder and not in my defined web root folder..
I found that it want create folder which is defined: $this->quarantine = $this->root.DIRECTORY_SEPARATOR.$this->options['quarantine'];
And that is the problem because I dont want it create in /images folder.
I can change it myself what I need, but with next update I must be very carefull and compare future changes with my improvement.
Is it possible on your site make next configuration for ".quarantine" folder? Something like : quarantineURL ?
I have similar specific configuration folder for tmbURL.

Thank you very much
Stan

**Comment by megadr01d** [comment]
Include in your connector file:

~~~php
// Documentation for connector options:
// https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options
$opts = array(
    'roots' => array(
        array(
            ...
            'quarantine' => '../.quarantine', // i'm using a relative path, you can try an absolute one
            ...
        )
    )
);
~~~

**Comment by standus** [comment]
Sorry, but in documentation is nothing about "quarantine".

**Comment by megadr01d** [comment]
You're right. I [learned it](https://github.com/nao-pon/elFinder-nightly/issues/4#issuecomment-103782457) from nao-pon so I think this option was just introduced in his nightly repo.

**Comment by nao-pon** [comment]
I wrote to wiki about option [quarantine](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#quarantine). Please rewrite strict English because my English is not good.

**Comment by megadr01d** [comment]
> Please rewrite strict English because my English is not good.

Revised and updated.

**Comment by nao-pon** [comment]
@megadr01d Thanks!

**Comment by megadr01d** [comment]
@standus

The Wiki says the default value for quarantine is `path/.quarantine` so

```
'path' => '/home/webspace/public_html',
'quarantine'  => '/.quarantine',
```

creates `/home/webspace/public_html/.quarantine`.

```php
'path' => '/home/webspace/public_html',
'quarantine'  => '../../../tmp/.quarantine',
```

creates `/tmp/.quarantine`
