### ISSUE TITLE
Reload button

### ISSUE THREAD

**Issue by megadr01d** [nao-pon/elFinder-nightly#14]
1. Right click on a file, you get the contextual menu
2. Click the Reload button in elFinder's Toolbar (or shortcut key)
3. Do step 1 and the contextual menu doesn't work
4. Click Reload again and the contextual menu works again

Safari 7.1.6.

**Comment by nao-pon** [comment]
Umm... It was no problem with 2.1 (Nightly: f234f03), jQuery/jQuery UI: 2.1.4/1.11.4, Safari 5.1.7 (Windows). How about on my [demo site](http://hypweb.net/elFinder-nightly/demo/2.1/)?

**Comment by megadr01d** [comment]
Okay, I was able to reproduce this on your demo site.

1. Access demo site [test folder](http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l2_bWVnYWRyMDFkLXRlc3Q)

2. Right click on any item and you get the contextual menu, click outside to dismiss

3. Reload (<kbd>Shift + Cmd + R</kbd> or right click on an empty space and choose Reload from the `cwd` contextual menu)

4. Right click on any item and the contextual menu doesn't work

5. Reload

6. Do step 2

7. Add `folder3` to Places

8. Reload

9. Right click on any item doesn't work expect `folder3` which works

10. Reload

11. Contextual menu works on all items

I tried this in other roots on your demo site and it worked correctly so maybe it only happens with the LocalFileSystem?

Also, If I click on my root drive in the navbar and try the tests above on the first level folders, it works correctly. If I enter a subfolder, it only works correctly if a folder is added to the Places as mentioned above.

No hurry, please take your time, this is a weird bug =)

**Comment by nao-pon** [comment]
@megadr01d Thanks!

**Comment by megadr01d** [comment]
@nao-pon Fixed :+1:
