### ISSUE TITLE
LocalFileSystem: Drag to same folder makes selection sticky

### ISSUE THREAD

**Issue by megadr01d** [nao-pon/elFinder-nightly#15]
@nao-pon Thanks, just to report that I'm not getting any console warnings in Safari 7.1.6 but I still get sticky selections (sorry if this is a different issue).

1. Access demo site [test folder](http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l2_bWVnYWRyMDFkLXRlc3Q)

2. Drag some folders and files to the empty space below (it works like when you press <kbd>Cmd/Ctrl + Click</kbd> to select multiple items)

Output: Every dragged item stays selected and is only unselected by clicking on it again. Shortcut actions like "remove" or "rename" stop working on these sticky items until reload.

Expected: Clicking on any item or empty space below should unselect everything

**Comment by nao-pon** [comment]
@megadr01d Thanks! :+1:

**Comment by megadr01d** [comment]
@nao-pon Thanks dragging is fixed but there is still a small exception. =]

1. Access [demo folder](http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l2_Lw)
2. Select an item, delete it (shortcut or contextual menu) but press "Cancel"
3. Select another item and see that the first selection sticks

Sorry, I'm a bug finder. =\

**Comment by nao-pon** [comment]
@megadr01d Thanks again ! :+1:

**Comment by megadr01d** [comment]
:+1: Thank you!
