### ISSUE TITLE
Expanding/collapsing arrows go nuts

### ISSUE THREAD

**Issue by megadr01d** [nao-pon/elFinder-nightly#16]
1. Access [demo folder](http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l2_Lw) (`Test here` should be selected)
2. Click on `untitled folder` in the Navbar (not the arrow but the folder name itself)
3. See how all arrows get expanded
4. Click on `untitled folder` again (now it reveals the subfolder correctly)
5. Click on the arrows of the untitled folders (no expanding/collapsing animation)
6. Reload your browser (not elFinder reload - <kbd>Cmd-R</kbd> or <kbd>F5</kbd>)
7. The `Test here` folder gets an inverted arrow. It's expanded showing the untitled folders but its arrow is collapsed (facing right)
8. Click on the `Test here` arrow and you see the contents collapse but the arrow is expanded (facing down)
9. Sorry that I find these things =/

Maybe this happened after the root reload fix (https://github.com/Studio-42/elFinder/commit/f234f03c71ac441eee0fcc3dd74a6ec4800e1ede or https://github.com/Studio-42/elFinder/commit/4f9fbe14eaabb6acdaa670f1198b985d57b98a64)?

```
I found another bug!
--------------------
        \
```

![nao-pon](http://www.cute-factor.com/images/smilies/onion/th_081_.gif) ![megadr01d](http://www.cute-factor.com/images/smilies/onion/df13952b.gif)
`nao-pon` `megadr01d`

**Comment by nao-pon** [comment]
@megadr01d Thanks for your report. You are great bugs finder! Please keep up the good work.  :+1:

**Comment by megadr01d** [comment]
:+1: Fixed. Thank you!
