### ISSUE TITLE
Navbar context menu

### ISSUE THREAD

**Issue by megadr01d** [nao-pon/elFinder-nightly#17]
Take the following context menu settings:

```js
contextmenu : {
    navbar : ['mkdir', 'mkfile', '|', '**rename**', '|', 'rm', '|', '**download**', 'places', '|', 'info'],
    files  : ['mkdir', 'mkfile', '|', '**rename**', '|', 'rm', '|', '**download**', 'places', '|', 'info']
}
```

1. Clear selection on file listing (click on empty area)
2. Right click on a folder in the Navbar

**Result**: The context menu **shows up  correctly** with `mkdir`, `mkfile`, `rm`, `places` and `info`.  
`**rename**` and `**download**` are not implemented for the Navbar, so they don't show up when right clicking, which is correct.

3. Select a file in the file listing
4. Right click on a folder in the Navbar

**Result**: The context menu shows up with `mkdir`, `mkfile`, `**rename**`, `rm`, `**download**`, `places` and `info`.  
`**rename**` and `**download**` **should not show up** since they're not implemented for the Navbar. If we select these options, they still work but apply to the selected file, not to the Navbar folder, which is confusing.

BTW, is the `rename` function already implemented for the Navbar but not used, or you think it should not be implemented? See relevant [issue](https://github.com/Studio-42/elFinder/issues/454).

**Comment by nao-pon** [comment]
Hi @megadr01d , About `rename` in navbar, its function is achieved shortly. But about `download`, I'm thinking how to do that.

**Comment by megadr01d** [comment]
Hi @nao-pon 

> About rename in navbar, its function is achieved shortly

This is highly appreciated, thank you very much for this functionality. Just tested it on your demo site and it's working great.

> But about download, I'm thinking how to do that

Actually, I was just saying this is not implemented for navbar (or file listing) as information. Maybe we don't need the option to download folders. We can just archive them and then download.

**Comment by megadr01d** [comment]
I just noticed that if `navbar : ['download']` is set and you select any file from the file listing, if you right click on any navbar folder, the "Download" option is available. Maybe you want to hide it all the time, file selected or not.
