### ISSUE TITLE
Rename multiple items

### ISSUE THREAD

**Issue by megadr01d** [nao-pon/elFinder-nightly#18]
Hi @nao-pon, this is low priority, just reporting.

1. Select more than 1 item (file or folder) in the file listing
2. Hit <kbd>F2</kbd> to invoke the `rename` command

Result: There's an error notice saying `Invalid parameters for command "Close".`
I think nothing should happen like the `preview` command (if you press <kbd>Space</kbd> on multiple items) or, alternatively, rename just the first selected item like the `open` command (which opens just the first selected item).

**Comment by nao-pon** [comment]
@megadr01d Thanks! It's enbug i'll fix. :-)

**Comment by megadr01d** [comment]
@nao-pon :+1:
