### ISSUE TITLE
Textarea focus

### ISSUE THREAD

**Issue by megadr01d** [nao-pon/elFinder-nightly#19]
@nao-pon Another low priority issue.

1. Select a text file and edit it
2. Hover any of the window buttons (`Cancel`, `Save & Close` or `Save`)

Result: The `textarea` loses the focus.

Optimal result:

- The `textarea` should always keep the focus when hovering any button with your mouse cursor
- After clicking `Save`, the focus should return to the `textarea`
- A feature request would be to implement a shortcut key to save the file (<kbd>Ctrl/Cmd + S</kbd> if `pevent.preventDefault()` can override the browser's default shortcut or, alternatively, another non-conflicting shortcut combination).

**Comment by nao-pon** [comment]
@megadr01d Thanks again!

<kbd>Ctrl/Cmd + S</kbd> is more effective than before. ;-)

**Comment by megadr01d** [comment]
@nao-pon Domo arigato Naoki-san!
Much easier to edit and save with keyboard only.

**Comment by nao-pon** [comment]
Wow! Good Japanese! ありがとう！(Arigatou !)
2015/07/09 18:39 "megadr01d" <notifications@github.com>:

**Comment by megadr01d** [comment]
I learned it from my ex Japanese girlfriend, Noriko Akiyama but I confess I just know a few setences. ^_^'
