### ISSUE TITLE
BUG: uploading big files via right-click doesn't get splitted in chunks

### ISSUE THREAD

**Issue by a-opazo** [nao-pon/elFinder-nightly#20]
Uploading big files with the upload icon, just gets chuncked and uploads go ok.

The problem is when the user uploads via the menu found when right-click is pressed inside the file panel, it offers the html5 upload window and the file can produce an error 500 in the server if is too big for the server to handle.

If this can't be solved in the html5 uploader, the is best to disable the right-click upload offering, and stick with the icon function only.

**Comment by nao-pon** [comment]
@a-opazo Thanks! :+1:
