### ISSUE TITLE
Elfinder 2.1: Sometimes you get double search box in the browser

### ISSUE THREAD

**Issue by a-opazo** [nao-pon/elFinder-nightly#21]
Sometimes (random), using the 2.1 nighly branch, the display shows something like this:

![ef21](https://cloud.githubusercontent.com/assets/13522780/8983476/9406b9d2-3698-11e5-84a3-3eb88dc7e60b.png)

The search box in the left is editable, but you can't delete anything or do search using it. The search box at the right is ok.

Doesn't seem to happen with the 2.x nightly branch, and one way to force it is to load the page, and then press CTRL+F5. For some reason it doesn't happen on the demo page though.

Tested on the lastest firefox stable, chrome, and MSIE 11, on windows 7 x64. Server is Debian 7.0 full updated, and also with the uniform server (wamp zero-config server for windows).

**Comment by nao-pon** [comment]
@a-opazo Thanks! :+1:
