### ISSUE TITLE
Question or feature request

### ISSUE THREAD

**Issue by a-opazo** [nao-pon/elFinder-nightly#22]
Is there a way to make elfinder generate a callback when:

- An error has ocurred (any, e.g.: "can't connect to backend" (e.g.: when php session is over and elfinder window is still open, a message is displayed, but as far i can see, there's no way to fire a javascript function to handle it, at least not without messing with the code).??
- All files have been uploaded/downloaded. (upload handler fires multiple times if chunk upload is used, for example. It seems there's no way to discern when multiple files are uploaded and the upload is finished.) ??

Thanks in advance for your answer and your time.

**Comment by nao-pon** [comment]
Hi @a-opazo ! Which side is it, connector or client?

**Comment by a-opazo** [comment]
Both are the the client. What i miss in the client handler API is an e.g. "error"  event that should be fired when an error occurs when the client connect to the server, and for the second case, the handler upload event is fired every time a file or chunck (when using the chunk upload feature) is uploaded. Don't know if is intended but there seems no way for the client to detect when all files are uploaded, and fire an event in this case. (e.g. upload event fires 30 times when a user upload 3 files of 10 mb each, instead to have an event that fires when the 3 files are uploaded).

Hope this describes the problems.

**Comment by nao-pon** [comment]
How about bind 'error' and check data.added in upload callback.

```javascript
elfinderInstance.bind('error', function(e) {
	elfinderInstance.log(e);
});

elfinderInstance.bind('upload', function(e) {
	if (e.data && e.data.added && e.data.added.length) {
		elfinderInstance.log(e);
	}
});

```

**Comment by a-opazo** [comment]
Fair enough. I will test them, thanks.
