### ISSUE TITLE
Dropbox with elFinder

### ISSUE THREAD

**Issue by rajasharma27** [nao-pon/elFinder-nightly#23]
Sir
I am using elfinder with dropbox, it working ok with dropbox when i mount with folder name but when i mounted with root without folder name its showing error "root folder does not exist" i am using full access dropbox api.

**Comment by nao-pon** [comment]
@rajasharma27 There is no problem in my test case. Please show me your connector configuration.

**Comment by nao-pon** [comment]
move to https://github.com/nao-pon/elFinder-nightly-src/issues/2
