### ISSUE TITLE
some bug using with elfinderBasicAuth.js on windows server

### ISSUE THREAD

**Issue by rajasharma27** [nao-pon/elFinder-nightly#24]
Sir,
some bug using with elfinderBasicAuth.js
in windows server always return Unauthorized
http://localhost:8080/elfinder-2.1.4/php/connector.minimal.php?login 401 (Unauthorized)

**Comment by nao-pon** [comment]
I checked on XAMPP 1.8.1 (Apache/2.4.3 (Win32) OpenSSL/1.0.1c PHP/5.4.7). It work fine. What is your server environment?

**Comment by rajasharma27** [comment]
i checked on windows7

**Comment by rajasharma27** [comment]
i checked on windows7 and PHP 5.4

**Comment by rajasharma27** [comment]
i am using this code

//***** basic auth section *****/
session_start();
$admins = array('admin' => true);
if (isset($_GET['login']) || isset($_GET['logout']) || isset($_GET['status'])) {
	$auths = array(
		'admin' => 'pass',
		'demouser' => 'demouser'
	);
	if (!isset($_SERVER['PHP_AUTH_USER']) && !isset($_GET['status'])) {
		header("WWW-Authenticate: Basic realm=\"lockfolder\"");
		header("HTTP/1.0 401 Unauthorized");
		echo '{"error": "Login faild."}';
		exit;
	} else {
		//	|| !isset($_SESSION['ELFINDER_AUTH_USER']) || $_SERVER['PHP_AUTH_USER'] !== $_SESSION['ELFINDER_AUTH_USER']
		if (isset($_GET['logout'])) {
			unset($_SESSION['ELFINDER_AUTH_USER']);
			echo '{"uname": ""}';
		} else {
			if (isset($_SERVER['PHP_AUTH_USER']) && isset($auths[$_SERVER['PHP_AUTH_USER']]) && $auths[$_SERVER['PHP_AUTH_USER']] === $_SERVER['PHP_AUTH_PW']) {
				if (isset($_GET['status'])) {
					echo '{"uname": "'.(isset($_SESSION['ELFINDER_AUTH_USER'])? $_SESSION['ELFINDER_AUTH_USER'] : '').'"}';
				} else {
					$_SESSION['ELFINDER_AUTH_USER'] = $_SERVER['PHP_AUTH_USER'];
					echo '{"uname": "'.$_SERVER['PHP_AUTH_USER'].'"}';
				}
			} else {
				if (isset($_GET['status'])) {
					echo '{"uname": ""}';
				} else {
					header("WWW-Authenticate: Basic realm=\"lockfolder\"");
					header("HTTP/1.0 401 Unauthorized");
					echo '{"error": "Login faild."}';
					exit;
				}
			}
		}
	}
	exit();
}
$uname = '';
if (!empty($_SESSION['ELFINDER_AUTH_USER']) && !empty($_SERVER['PHP_AUTH_USER'])) {
	$uname = ($_SESSION['ELFINDER_AUTH_USER'] === $_SERVER['PHP_AUTH_USER'])? $_SERVER['PHP_AUTH_USER'] : '';
}
$isAdmin = isset($admins[$uname]);
$isUser = $uname? true : false;
/******************************

**Comment by nao-pon** [comment]
Please check `$_SERVER` & `$_GET`.

Example code
```php
function debug() {
	$args = func_get_args();
	ob_start();
	foreach($args as $arg) {
		//debug_print_backtrace();
		var_dump($arg);
	}
	$str = ob_get_clean();
	file_put_contents(dirname(__FILE__) . '/debug.txt', $str . "\n", FILE_APPEND);
}
//***** basic auth section *****/
session_start();
$admins = array('admin' => true);
if (isset($_GET['login']) || isset($_GET['logout']) || isset($_GET['status'])) {
    debug($_SERVER, $_GET);
    $auths = array(
        'admin' => 'pass',
        'demouser' => 'demouser'
    );
    ...
```
```

**Comment by rajasharma27** [comment]
array(87) {
  ["_FCGI_X_PIPE_"]=>
  string(53) "\\.\pipe\IISFCGI-dda3c378-f1e9-4bb9-8efe-f56535f38d70"
  ["PHP_FCGI_MAX_REQUESTS"]=>
  string(5) "10000"
  ["PHPRC"]=>
  string(21) "C:\Program Files\PHP\"
  ["ALLUSERSPROFILE"]=>
  string(14) "C:\ProgramData"
  ["APPDATA"]=>
  string(56) "C:\Windows\system32\config\systemprofile\AppData\Roaming"
  ["APP_POOL_CONFIG"]=>
  string(61) "C:\inetpub\temp\apppools\DefaultAppPool\DefaultAppPool.config"
  ["APP_POOL_ID"]=>
  string(14) "DefaultAppPool"
  ["CLASSPATH"]=>
  string(47) ".;C:\Program Files\Java\jre7\lib\ext\QTJava.zip"
  ["CommonProgramFiles"]=>
  string(29) "C:\Program Files\Common Files"
  ["COMPUTERNAME"]=>
  string(12) "COMPUTER1"
  ["ComSpec"]=>
  string(27) "C:\Windows\system32\cmd.exe"
  ["FP_NO_HOST_CHECK"]=>
  string(2) "NO"
  ["LOCALAPPDATA"]=>
  string(54) "C:\Windows\system32\config\systemprofile\AppData\Local"
  ["NUMBER_OF_PROCESSORS"]=>
  string(1) "4"
  ["OS"]=>
  string(10) "Windows_NT"
  ["Path"]=>
  string(277) "C:\ProgramData\Oracle\Java\javapath;C:\Program Files\PHP\;C:\Program Files\Dell\DW WLAN Card;;;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\QuickTime\QTSystem\;"
  ["PATHEXT"]=>
  string(53) ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
  ["PROCESSOR_ARCHITECTURE"]=>
  string(3) "x86"
  ["PROCESSOR_IDENTIFIER"]=>
  string(46) "x86 Family 6 Model 37 Stepping 5, GenuineIntel"
  ["PROCESSOR_LEVEL"]=>
  string(1) "6"
  ["PROCESSOR_REVISION"]=>
  string(4) "2505"
  ["ProgramData"]=>
  string(14) "C:\ProgramData"
  ["ProgramFiles"]=>
  string(16) "C:\Program Files"
  ["PSModulePath"]=>
  string(51) "C:\Windows\system32\WindowsPowerShell\v1.0\Modules\"
  ["PUBLIC"]=>
  string(15) "C:\Users\Public"
  ["QTJAVA"]=>
  string(45) "C:\Program Files\Java\jre7\lib\ext\QTJava.zip"
  ["SystemDrive"]=>
  string(2) "C:"
  ["SystemRoot"]=>
  string(10) "C:\Windows"
  ["TEMP"]=>
  string(15) "C:\Windows\TEMP"
  ["TMP"]=>
  string(15) "C:\Windows\TEMP"
  ["USERDOMAIN"]=>
  string(9) "WORKGROUP"
  ["USERNAME"]=>
  string(13) "ADMINISTRATOR$"
  ["USERPROFILE"]=>
  string(40) "C:\Windows\system32\config\systemprofile"
  ["windir"]=>
  string(10) "C:\Windows"
  ["FCGI_ROLE"]=>
  string(9) "RESPONDER"
  ["HTTP_CONNECTION"]=>
  string(10) "keep-alive"
  ["HTTP_ACCEPT"]=>
  string(46) "application/json, text/javascript, */*; q=0.01"
  ["HTTP_ACCEPT_ENCODING"]=>
  string(19) "gzip, deflate, sdch"
  ["HTTP_ACCEPT_LANGUAGE"]=>
  string(14) "en-US,en;q=0.8"
  ["HTTP_COOKIE"]=>
  string(113) "ajaxchat=hi%09%09LORc6nYRy0%092%091%091%091%092%092%092%092%092%092%092%092; PHPSESSID=65nuu2faf586moiijspbopg000"
  ["HTTP_HOST"]=>
  string(14) "localhost:8080"
  ["HTTP_REFERER"]=>
  string(33) "http://localhost:8080/elfinder2x/"
  ["HTTP_USER_AGENT"]=>
  string(102) "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
  ["HTTP_X_REQUESTED_WITH"]=>
  string(14) "XMLHttpRequest"
  ["APPL_MD_PATH"]=>
  string(16) "/LM/W3SVC/2/ROOT"
  ["APPL_PHYSICAL_PATH"]=>
  string(8) "D:\demo\"
  ["AUTH_TYPE"]=>
  string(0) ""
  ["AUTH_PASSWORD"]=>
  string(0) ""
  ["AUTH_USER"]=>
  string(0) ""
  ["CERT_COOKIE"]=>
  string(0) ""
  ["CERT_FLAGS"]=>
  string(0) ""
  ["CERT_ISSUER"]=>
  string(0) ""
  ["CERT_SERIALNUMBER"]=>
  string(0) ""
  ["CERT_SUBJECT"]=>
  string(0) ""
  ["CONTENT_LENGTH"]=>
  string(1) "0"
  ["CONTENT_TYPE"]=>
  string(0) ""
  ["DOCUMENT_ROOT"]=>
  string(7) "D:\demo"
  ["GATEWAY_INTERFACE"]=>
  string(7) "CGI/1.1"
  ["HTTPS"]=>
  string(3) "off"
  ["HTTPS_KEYSIZE"]=>
  string(0) ""
  ["HTTPS_SECRETKEYSIZE"]=>
  string(0) ""
  ["HTTPS_SERVER_ISSUER"]=>
  string(0) ""
  ["HTTPS_SERVER_SUBJECT"]=>
  string(0) ""
  ["INSTANCE_ID"]=>
  string(1) "2"
  ["INSTANCE_NAME"]=>
  string(4) "demo"
  ["INSTANCE_META_PATH"]=>
  string(11) "/LM/W3SVC/2"
  ["LOCAL_ADDR"]=>
  string(3) "::1"
  ["LOGON_USER"]=>
  string(0) ""
  ["PATH_TRANSLATED"]=>
  string(44) "D:\demo\elfinder2x\php\connector.minimal.php"
  ["QUERY_STRING"]=>
  string(6) "status"
  ["REMOTE_ADDR"]=>
  string(3) "::1"
  ["REMOTE_HOST"]=>
  string(3) "::1"
  ["REMOTE_PORT"]=>
  string(5) "18048"
  ["REMOTE_USER"]=>
  string(0) ""
  ["REQUEST_METHOD"]=>
  string(3) "GET"
  ["REQUEST_URI"]=>
  string(44) "/elfinder2x/php/connector.minimal.php?status"
  ["SCRIPT_FILENAME"]=>
  string(44) "D:\demo\elfinder2x\php\connector.minimal.php"
  ["SCRIPT_NAME"]=>
  string(37) "/elfinder2x/php/connector.minimal.php"
  ["SERVER_NAME"]=>
  string(9) "localhost"
  ["SERVER_PORT"]=>
  string(4) "8080"
  ["SERVER_PORT_SECURE"]=>
  string(1) "0"
  ["SERVER_PROTOCOL"]=>
  string(8) "HTTP/1.1"
  ["SERVER_SOFTWARE"]=>
  string(17) "Microsoft-IIS/7.5"
  ["URL"]=>
  string(37) "/elfinder2x/php/connector.minimal.php"
  ["ORIG_PATH_INFO"]=>
  string(37) "/elfinder2x/php/connector.minimal.php"
  ["PHP_SELF"]=>
  string(37) "/elfinder2x/php/connector.minimal.php"
  ["REQUEST_TIME"]=>
  int(1450747210)
}
array(1) {
  ["status"]=>
  string(0) ""
}

array(87) {
  ["_FCGI_X_PIPE_"]=>
  string(53) "\\.\pipe\IISFCGI-dda3c378-f1e9-4bb9-8efe-f56535f38d70"
  ["PHP_FCGI_MAX_REQUESTS"]=>
  string(5) "10000"
  ["PHPRC"]=>
  string(21) "C:\Program Files\PHP\"
  ["ALLUSERSPROFILE"]=>
  string(14) "C:\ProgramData"
  ["APPDATA"]=>
  string(56) "C:\Windows\system32\config\systemprofile\AppData\Roaming"
  ["APP_POOL_CONFIG"]=>
  string(61) "C:\inetpub\temp\apppools\DefaultAppPool\DefaultAppPool.config"
  ["APP_POOL_ID"]=>
  string(14) "DefaultAppPool"
  ["CLASSPATH"]=>
  string(47) ".;C:\Program Files\Java\jre7\lib\ext\QTJava.zip"
  ["CommonProgramFiles"]=>
  string(29) "C:\Program Files\Common Files"
  ["COMPUTERNAME"]=>
  string(12) "COMPUTER1"
  ["ComSpec"]=>
  string(27) "C:\Windows\system32\cmd.exe"
  ["FP_NO_HOST_CHECK"]=>
  string(2) "NO"
  ["LOCALAPPDATA"]=>
  string(54) "C:\Windows\system32\config\systemprofile\AppData\Local"
  ["NUMBER_OF_PROCESSORS"]=>
  string(1) "4"
  ["OS"]=>
  string(10) "Windows_NT"
  ["Path"]=>
  string(277) "C:\ProgramData\Oracle\Java\javapath;C:\Program Files\PHP\;C:\Program Files\Dell\DW WLAN Card;;;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\QuickTime\QTSystem\;"
  ["PATHEXT"]=>
  string(53) ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
  ["PROCESSOR_ARCHITECTURE"]=>
  string(3) "x86"
  ["PROCESSOR_IDENTIFIER"]=>
  string(46) "x86 Family 6 Model 37 Stepping 5, GenuineIntel"
  ["PROCESSOR_LEVEL"]=>
  string(1) "6"
  ["PROCESSOR_REVISION"]=>
  string(4) "2505"
  ["ProgramData"]=>
  string(14) "C:\ProgramData"
  ["ProgramFiles"]=>
  string(16) "C:\Program Files"
  ["PSModulePath"]=>
  string(51) "C:\Windows\system32\WindowsPowerShell\v1.0\Modules\"
  ["PUBLIC"]=>
  string(15) "C:\Users\Public"
  ["QTJAVA"]=>
  string(45) "C:\Program Files\Java\jre7\lib\ext\QTJava.zip"
  ["SystemDrive"]=>
  string(2) "C:"
  ["SystemRoot"]=>
  string(10) "C:\Windows"
  ["TEMP"]=>
  string(15) "C:\Windows\TEMP"
  ["TMP"]=>
  string(15) "C:\Windows\TEMP"
  ["USERDOMAIN"]=>
  string(9) "WORKGROUP"
  ["USERNAME"]=>
  string(13) "ADMINISTRATOR$"
  ["USERPROFILE"]=>
  string(40) "C:\Windows\system32\config\systemprofile"
  ["windir"]=>
  string(10) "C:\Windows"
  ["FCGI_ROLE"]=>
  string(9) "RESPONDER"
  ["HTTP_CONNECTION"]=>
  string(10) "keep-alive"
  ["HTTP_ACCEPT"]=>
  string(46) "application/json, text/javascript, */*; q=0.01"
  ["HTTP_ACCEPT_ENCODING"]=>
  string(19) "gzip, deflate, sdch"
  ["HTTP_ACCEPT_LANGUAGE"]=>
  string(14) "en-US,en;q=0.8"
  ["HTTP_COOKIE"]=>
  string(113) "ajaxchat=hi%09%09LORc6nYRy0%092%091%091%091%092%092%092%092%092%092%092%092; PHPSESSID=65nuu2faf586moiijspbopg000"
  ["HTTP_HOST"]=>
  string(14) "localhost:8080"
  ["HTTP_REFERER"]=>
  string(33) "http://localhost:8080/elfinder2x/"
  ["HTTP_USER_AGENT"]=>
  string(102) "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
  ["HTTP_X_REQUESTED_WITH"]=>
  string(14) "XMLHttpRequest"
  ["APPL_MD_PATH"]=>
  string(16) "/LM/W3SVC/2/ROOT"
  ["APPL_PHYSICAL_PATH"]=>
  string(8) "D:\demo\"
  ["AUTH_TYPE"]=>
  string(0) ""
  ["AUTH_PASSWORD"]=>
  string(0) ""
  ["AUTH_USER"]=>
  string(0) ""
  ["CERT_COOKIE"]=>
  string(0) ""
  ["CERT_FLAGS"]=>
  string(0) ""
  ["CERT_ISSUER"]=>
  string(0) ""
  ["CERT_SERIALNUMBER"]=>
  string(0) ""
  ["CERT_SUBJECT"]=>
  string(0) ""
  ["CONTENT_LENGTH"]=>
  string(1) "0"
  ["CONTENT_TYPE"]=>
  string(0) ""
  ["DOCUMENT_ROOT"]=>
  string(7) "D:\demo"
  ["GATEWAY_INTERFACE"]=>
  string(7) "CGI/1.1"
  ["HTTPS"]=>
  string(3) "off"
  ["HTTPS_KEYSIZE"]=>
  string(0) ""
  ["HTTPS_SECRETKEYSIZE"]=>
  string(0) ""
  ["HTTPS_SERVER_ISSUER"]=>
  string(0) ""
  ["HTTPS_SERVER_SUBJECT"]=>
  string(0) ""
  ["INSTANCE_ID"]=>
  string(1) "2"
  ["INSTANCE_NAME"]=>
  string(4) "DEMO"
  ["INSTANCE_META_PATH"]=>
  string(11) "/LM/W3SVC/2"
  ["LOCAL_ADDR"]=>
  string(3) "::1"
  ["LOGON_USER"]=>
  string(0) ""
  ["PATH_TRANSLATED"]=>
  string(44) "D:\demo\elfinder2x\php\connector.minimal.php"
  ["QUERY_STRING"]=>
  string(5) "login"
  ["REMOTE_ADDR"]=>
  string(3) "::1"
  ["REMOTE_HOST"]=>
  string(3) "::1"
  ["REMOTE_PORT"]=>
  string(5) "18048"
  ["REMOTE_USER"]=>
  string(0) ""
  ["REQUEST_METHOD"]=>
  string(3) "GET"
  ["REQUEST_URI"]=>
  string(43) "/elfinder2x/php/connector.minimal.php?login"
  ["SCRIPT_FILENAME"]=>
  string(44) "D:\demo\elfinder2x\php\connector.minimal.php"
  ["SCRIPT_NAME"]=>
  string(37) "/elfinder2x/php/connector.minimal.php"
  ["SERVER_NAME"]=>
  string(9) "localhost"
  ["SERVER_PORT"]=>
  string(4) "8080"
  ["SERVER_PORT_SECURE"]=>
  string(1) "0"
  ["SERVER_PROTOCOL"]=>
  string(8) "HTTP/1.1"
  ["SERVER_SOFTWARE"]=>
  string(17) "Microsoft-IIS/7.5"
  ["URL"]=>
  string(37) "/elfinder2x/php/connector.minimal.php"
  ["ORIG_PATH_INFO"]=>
  string(37) "/elfinder2x/php/connector.minimal.php"
  ["PHP_SELF"]=>
  string(37) "/elfinder2x/php/connector.minimal.php"
  ["REQUEST_TIME"]=>
  int(1450747213)
}
array(1) {
  ["login"]=>
  string(0) ""
}

**Comment by rajasharma27** [comment]
this is debug output

**Comment by nao-pon** [comment]
What about http://stackoverflow.com/questions/17018586/apache-2-4-php-fpm-and-authorization-headers ?

**Comment by rajasharma27** [comment]
ok sir,
now is working.
but how to set different folder for different user.

**Comment by rajasharma27** [comment]
some problem in logout
when i login one user and logout. and  login with another user. it always connect only one user who is login first. logout session not destroy for another user.

**Comment by nao-pon** [comment]
> but how to set different folder for different user.

example
```
'path'          => '../'.$uname.'/',
'URL'           => dirname($_SERVER['PHP_SELF']) . '/../'.$uname.'/',
```

> some problem in logout

To completely log out in the Basic authentication you must close the browser. This is the specification of the Basic authentication.
