### ISSUE TITLE
Two elFinder instance on same page not work

### ISSUE THREAD

**Issue by rajasharma27** [nao-pon/elFinder-nightly#26]
Sir, i am facing problem with two elFinder instance on same page.
first instance work fine, but second instance missing or hide folder tree view.

**Comment by rajasharma27** [comment]
this issue facing when first elFinder and second ckEditor with elfinder both using on same page.
in the ckEditor browse elfinder not showing folder tree view.

**Comment by rajasharma27** [comment]
this code for ckeditor

(function(){
        var elfNode, elfInsrance, dialogName,
            elfUrl        = 'elfinder/php/connector.minimal.php', // Your connector's URL
            elfDirHashMap = { // Dialog name / elFinder holder hash Map
                image : 'l1_SW1hZ2Vz', // example for 1st LocalFileVolume "/images"
                flash : '',
                files : '',
                link  : ''
            };
            var getLang = function() {
                try {
                    var full_lng;
                    var loct = window.location.search;
                    var locm;
                    if (loct && (locm = loct.match(/lang=([a-zA-Z_-]+)/))) {
                        full_lng = locm[1];
                    } else {
                        full_lng = (navigator.browserLanguage || navigator.language || navigator.userLanguage);
                    }
                    var lng = full_lng.substr(0,2);
                    if (lng == 'ja') lng = 'jp';
                    else if (lng == 'pt') lng = 'pt_BR';
                    else if (lng == 'zh') lng = (full_lng.substr(0,5) == 'zh-tw')? 'zh_TW' : 'zh_CN';

                    if (lng != 'en') {
                        var script_tag      = document.createElement("script");
                        script_tag.type     = "text/javascript";
                        script_tag.src      = "./js/i18n/elfinder."+lng+".js";
                        script_tag.charset = "utf-8";
                        $("head").append(script_tag);
                    }

                    return lng;
                } catch(e) {
                    return 'en';
                }
            };

        CKEDITOR.on('dialogDefinition', function (event) { // connection manager
            var editor = event.editor;
            var dialogDefinition = event.data.definition;
            var tabCount = dialogDefinition.contents.length;
            for (var i = 0; i < tabCount; i++) { // cycle to replace the click of button "View on the server"
                var browseButton = dialogDefinition.contents[i].get('browse');

                if (browseButton !== null) {
                    browseButton.hidden = false;
                    browseButton.onClick = function (dialog, i) {

                        dialogName = CKEDITOR.dialog.getCurrent()._.name;
                        if (elfNode) {
                            if (elfDirHashMap[dialogName] && elfDirHashMap[dialogName] != elfInsrance.cwd().hash) {
                                elfInsrance.request({
                                    data   : {cmd  : 'open', target : elfDirHashMap[dialogName]},
                                    notify : {type : 'open', cnt : 1, hideCnt : true},
                                    syncOnFail : true
                                });
                            }
                            elfNode.dialog('open');
                        } else {
                            elfNode = $('<div \>');
                            elfNode.dialog({
                                modal: true,
                                width: '80%',
                                title: 'Server File Manager',
                                create: function (event, ui) {
                                    var startPathHash = (elfDirHashMap[dialogName] && elfDirHashMap[dialogName])? elfDirHashMap[dialogName] : '';
                                                                        // elFinder configure
                                    elfInsrance = $(this).elfinder({
                                        startPathHash: startPathHash,
                                        useBrowserHistory: false,
                                        resizable: false,
                                        width: '100%',
                                        url: elfUrl,
                                        lang: getLang(),
                                        getFileCallback: function (file) {
                                            var url = file.url;
                                            var dialog = CKEDITOR.dialog.getCurrent();
                                            if (dialogName == 'image') {
                                                var urlObj = 'txtUrl'
                                            } else if (dialogName == 'flash') {
                                                var urlObj = 'src'
                                            } else if (dialogName == 'files' || dialogName == 'link') {
                                                var urlObj = 'url'
                                            } else {
                                                return;
                                            }
                                            dialog.setValueOf(dialog._.currentTabId, urlObj, url);
                                            elfNode.dialog('close');
                                            elfInsrance.disable();
                                        }
                                    }).elfinder('instance');
                                },
                                open: function() {
                                    elfNode.find('div.elfinder-toolbar input').blur();
                                    setTimeout(function(){
                                        elfInsrance.enable();
                                    }, 100);
                                },
                                resizeStop: function() {
                                    elfNode.trigger('resize');
                                }
                            }).parent().css({'zIndex':'11000'});
                        }

                    } 
                } 

            } 
        });
        })();

**Comment by nao-pon** [comment]
@rajasharma27 OK, Please move to Studio-42/elFinder#1174 .

**Comment by rajasharma27** [comment]
thanks sir,
now is working fine
