### ISSUE TITLE
missing dropbox unmount in menu

### ISSUE THREAD

**Issue by rajasharma27** [nao-pon/elFinder-nightly#27]
Sir, 
bug in dropbox unmount

when i mount to root only with "/" then missing unmount from menu
but when i mount with folder name "/demo" then is showing unmount in menu

**Comment by rajasharma27** [comment]
after 2 or more times refresh is showing but sometime not showing after refress

**Comment by nao-pon** [comment]
@rajasharma27 Thanks! From the next, it is OK that is if posted to issues on [Studio-42/elFinder
](https://github.com/Studio-42/elFinder/issues).

**Comment by rajasharma27** [comment]
Thanks
now is working perfectly.
