### ISSUE TITLE
uploadDeny not work with specific folder

### ISSUE THREAD

**Issue by rajasharma27** [nao-pon/elFinder-nightly#29]
how to these attribute use with specific folder not for all driver

   ‘uploadAllow’ => array(‘image/png’),
   ‘uploadDeny’  => array(‘image’, ‘text’),
   ‘uploadOrder’ => ‘deny,allow’

**Comment by rajasharma27** [comment]
thanks

**Comment by nao-pon** [comment]
@rajasharma27 I am looking forward to [Pull Request of GitHub](https://help.github.com/articles/using-pull-requests/). :-)
