### ISSUE TITLE
Dropbox Error elFinder 2.1.6

### ISSUE THREAD

**Issue by rajasharma27** [nao-pon/elFinder-nightly#33]
Sir,
dropbox mount first or second attempt always reject and  showing error "files or folder not found"

**Comment by nao-pon** [comment]
@rajasharma27 This is a bug of 2.1.6. It was fixed at https://github.com/Studio-42/elFinder/commit/a619bf43c532e9d8ec8f9406bb82e812bd0f1e86 . Please try nightly version - https://github.com/Studio-42/elFinder/tree/2.1 .

Thanks!

**Comment by rajasharma27** [comment]
i am using 2.1.6 from http://studio-42.github.io/elFinder/#elf_l1_Lw
same problem with ftp and dropbox  on windows server
