### ISSUE TITLE
Can't extract some archives

### ISSUE THREAD

**Issue by ghost** [nao-pon/elFinder-nightly#4]
On the latest 2.1 and 2.1_n, when extracting some archives I get **For security reason denied to unpack archives contains symlinks.**
In `connector.minimal.php` I have:

~~~ {.php}
'path'          => '../../../',
'URL'           => dirname($_SERVER['PHP_SELF']) . '/../../../../'
~~~

which makes elFinder's root outside of elFinder's folder (`public_html`, not `elfinder/files`). With the security above, no archive is extracted to the `.quarantine` folder.

- Is there any way to disable the symlink security?
- Is there a way to fix the `.quarantine` folder when elFinder's root is outside its own folder?

**Comment by nao-pon** [comment]
try use `quarantine` option
ex
```
'quarantine' => '/tmp'
```

And 
> Is there any way to disable the symlink security?
We can't  to disable of symlink check.

**Comment by megadr01d** [comment]
@nao-pon You can close this one. It was started by me with a different ID long ago and it's solved now.
