### ISSUE TITLE
Invalid UTF-8 sequence in argument

### ISSUE THREAD

**Issue by standus** [nao-pon/elFinder-nightly#6]
Some times I got error message:
json_encode(): Invalid UTF-8 sequence in argument
elFinderVolumeDriver.class.php on line:
// fix name if required
if ($this->options['utf8fix'] && $this->options['utf8patterns'] && $this->options['utf8replace']) {
$stat['name'] = json_decode(str_replace($this->options['utf8patterns'], $this->options['utf8replace'], json_encode($s)));}
I found some solutions:
http://stackoverflow.com/questions/4663743/how-to-keep-json-encode-from-dropping-strings-with-invalid-characters
Is it possible to fix it please?

**Comment by standus** [comment]
This helped for me:
$text = $stat['name'];
		$regex = '/( [\x00-\x7F] | [\xC0-\xDF][\x80-\xBF] | [\xE0-\xEF][\x80-\xBF]{2} | [\xF0-\xF7][\x80-\xBF]{3} ) | ./x';
		$text = preg_replace($regex, '$1', $text);
and then: json_encode($text,JSON_UNESCAPED_UNICODE) //for PHP >=5.4

**Comment by nao-pon** [comment]
@standus What is your server Filesystem encoding? Please try connector configuration [`encoding` and `locale` ](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding). Or 2.1 plugin [normalizer](https://github.com/Studio-42/elFinder/blob/2.1/php/plugins/Normalizer/plugin.php).
