### ISSUE TITLE
Option for text editor window size

### ISSUE THREAD

**Issue by megadr01d** [nao-pon/elFinder-nightly#7]
For Quick Look, it's easy to set a width and height in options. For the text editor, I have to hack the text area function and change the `rows` and `width` vars.

~~~
ta = $('<textarea class="elfinder-file-edit" rows="32" id="'+id+'-ta">'+fm.escape(content)+'</textarea>'),
...
width: self.options.dialogWidth || 980,
~~~

How can I turn those 2 values into options?

~~~
edit : {
			width	 : 980,
			height	 : 32
		},
~~~

**Comment by nao-pon** [comment]
@megadr01d, you can set commandsOptions - edit - dialogWidth

ex.
```
commandsOptions : {
	edit : {
		dialogWidth: 980
	}
}
```

about "height", there is not option. but you can use CSS
ex.
```
div.ui-dialog-content textarea.elfinder-file-edit {
	height: 32em;
}
```

**Comment by megadr01d** [comment]
:+1: Thanks a lot, nao-pon! And thanks for keeping up elFinder's development.
BTW, you can close [this](https://github.com/nao-pon/elFinder-nightly/issues/4) issue. It was started by me a long time ago with a GitHub ID I don't have anymore.
