### ISSUE TITLE
Unable to connect to backend. Backend not found.

### ISSUE THREAD

**Issue by Khudher** [nao-pon/elFinder-nightly#9]
Hello,

I'm having problems with this version of efFinder (2.1), I tried 2.0 RC and it worked perfectly, but seems to have some problems with this one, I want this version because i want elFinder to support touch screens, how can i solve this error? (I don't know how to set it up), and if this error can't be solved, how can i make 2.0 support touchscreens??

Thanks !

**Comment by megadr01d** [comment]
If you have set the connector options correctly and if you're accessing elFinder securely (https), you need to change jQuery links in `index.html` to https as well.

**Comment by Khudher** [comment]
how to set connector options?? can you tell me please?

**Comment by megadr01d** [comment]
It's the same as v2.0. In `index.html` set

~~~js
$(document).ready(function() {
    $('#elfinder').elfinder({
        url : 'php/connector.php'  // connector URL (REQUIRED)
    });
});
~~~

Then in the `php` dir copy `connector.php-dist` to `connector.php` and edit it. Documentation [link](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options) is in the comments but the default values should connect fine and give you access to the default `files` folder inside elFinder's install folder.

**Comment by Khudher** [comment]
hmm, how to embed that code into html?? it is javascript right??

and about the documentation https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options, can you explain this part => "'driver' => 'LocalFileSystem',"

Thanks!

**Comment by Khudher** [comment]
as you said it worked! much appreciated!

**Comment by megadr01d** [comment]
:+1:

**Comment by megadr01d** [comment]
@Khudher Don't forget to close this issue when you're set.
